URL_SERVICE = "https://cnt-ca19530b-cbbf-4a6b-89d5-b54661642819.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users"
KITS_PATH = "/api/v1/kits"
DOC_PATH = "/docs/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"